# --------------
# -- Settings --
# --------------

# If you are hosting in a sub-folder, for example: https://mlh.github.io/mlh-hackathon-boilerplate/,
# you must specify it as the baseurl
# If you hosting as a root, for example: htttps://[github username].github.io, then leave it blank
baseurl: "/NGPiTECH-henosis"

# uncomment the next line if you are hosting as a root and not sub-folder
# for example, when runnig locally at http://127.0.0.1:4000/
# baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "https://surprisedPikachu007.github.io"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-43729070-14"

# Let people connect & engage with you through social media.
social:
  twitter_handle: "drngpit"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "Henosis | 25 February 2023"
  description: "Henosis, the National level tech fest conducted by the Departmet of Computer Science and Engineering at NGPiTECH."
  image:       "https://www.drngpit.ac.in/assets/images/logo/ngp-itech-logo.png"

# Event information.
event:
  name:        "Henosis 2K23"
  description: "Henosis, A National level tech fest conducted by the Departmet of Computer Science and Engineering at NGPiTECH."
  date:        "25 February 2023"
  location:    "Coimbatore, Tamil Nadu, India"

  trust_badge:
    year:   "2017"  # season year
    region: "eu"    # "na" or "eu"
    color:  "white" # "white", "black", "gray", "red", "blue" or "yellow"

  hero:
    links:
      - text: "Register Here"
        my_mlh:
          client_id:    "0e2f9fc2921d3ad3e12ae900af630d09382e1b3dc1b5b50de2b01b70ad64dbee"
          redirect_uri: "https://docs.google.com/forms/d/e/1FAIpQLSczPY6dCAUdvDTifDieIFfnUqPP31nNSd2ZCAfk8m3VU7GLDg/viewform"
      

  about:
    description: >
      This is a one day event. There are four technical events which are fun. And OH!, did we forget to mention that there are exciting rewards for the top participants.

  # Info Sections
  info:
    sections:
      - image: "images/image1.png"
        title: "THINK."
        description: >
           Think big, start small
      - image: "images/image2.png"
        title: "CREATE."
        description: >
          Create a vision, make it a reality.
      - image: "images/image3.png"
        title: "INNOVATE."
        description: >
          Innovate to solve problems and create solutions.

  # Frequently asked questions.
  faq:
    - question: "What are the events conducted?"
      answer: >
        There are four technical events: paper presentation, 
        project presentation, code wars and wise quacks. 
    - question: "How many members can participate as a team?"
      answer: >
        For team competitions such as paper and project presentations there can be upto 4 members
        per team, for wisequacks upto 2 members per team and for code wars only individuals can participate.
    - question: "At what time will the event commence?"
      answer: >
        The event begins promptly at 9 a.m. IST.
    - question: "How much is the registration fee?"
      answer: >
        For technical events, the registration fee is Rs. 150. For workshops, the registration fee is Rs. 200. A participant can register for both the events. For technical events the participant can participate in any number of events.
    - question: "Should we pay for individual events?"
      answer: >
        No, the registration fee is for all the technical events. You can participate in any number of events.
    - question: "How to pay the registration fee?"
      answer: >
        The registration fee can only be paid on-site.
    - question: "What is the last date to register?"
      answer: >
        The last date to register is 25th February 2023. On-site registrations is available.
    - question: "What is the registration amount to be paid per team?"
      answer: >
        Individual registration fee is Rs. 150. So, for a team of 4 members, the registration fee is Rs. 600.
    - question: "What are the rules for paper presentation?"
      answer: >
        Rules for all the events are available in the events section above.
    - question: "What are the timings for the events?"
      answer: >
        The timings will be announced on the day of the event.
    - question: "Accommodation?"
      answer: >
        Since the event is a one day event, accommodation is not provided.
    - question: "Food?"
      answer: >
        Food can be purchased from the canteen.
  # This is the message you'll receive once you've registered.
  register:
    message: >
      You'll receive more information closer to the hackathon.

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
