# --------------
# -- Settings --
# --------------

# Ignore this. This is only if you're hosting this in a sub-folder.
# If you're using GitHub pages, they automatically override this with the right value.
baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "https://aoganezo.github.io"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-102955394-1"

# Let people connect & engage with you through social media.
social:
  twitter_handle: "MLHacks"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "Demon Hacks | November 2017 | DemonHacks"
  description: "Demon Hacks."
  image:       "https://prime.mlh.io/img/logos/mlh-prime-color.svg"

# Event information.
event:
  name:        "Demon Hacks"
  description: "Pursue Greatness."
  date:        "November 2017"
  location:    "Chicago, IL, United States"

  trust_badge:
    year:   "2017"  # season year
    region: "eu"    # "na" or "eu"
    color:  "white" # "white", "black", "gray", "red", "blue" or "yellow"

  hero:
    links:
      - text: "Apply"
        my_mlh:
          client_id:    "0e2f9fc2921d3ad3e12ae900af630d09382e1b3dc1b5b50de2b01b70ad64dbee"
          redirect_uri: "https://mlh.github.io/mlh-hackathon-boilerplate/success.html"
      - text: "Sponsor"
        href: "mailto:sponsorship@website.com"

  about:
    description: >
      Demon Hacks is a hackathon hosted by DePaul University.
      This is your opportunity to describe your event, what to expect, where it is & anything unique to your event.
      Keep it straightforward, don't make it too long.

  # Info Sections
  #info:
    #sections:
      #- image: "images/image1.png"
        #title: "LEARN."
        #description: >
        #  We can write something nice with a graphic (as above) to make the event more appealing.
      #- image: "images/image2.png"
      #  title: "BUILD."
      #  description: >
      #    We can write something nice with a graphic (as above) to make the event more appealing.
      #- image: "images/image3.png"
      #  title: "SHARE."
      #  description: >
      #    We can write something nice with a graphic (as above) to make the event more appealing.

  # Frequently asked questions.
  faq:
    - question: "Where is Chicago?"
      answer: >
        [Right here](http://bfy.tw/1CQf)
    - question: "What is a hackathon?"
      answer: >
        A hackathon is an invention marathon. Students come together to build cool
        software & hardware hacks over 24-48 hours. It's [very beginner friendly](https://medium.com/@tfogo/hackathons-are-for-beginners-77a9c9c0e000#.cj21niskl).
    - question: "How much does it cost?"
      answer: >
        Nothing, attending a hackathon is free!
    - question: "Do I need to be a student to attend?"
      answer: >
        Yes. Only students who are currently enrolled at a college/university or
        have graduated within the past 12 months are eligible to attend.
    - question: "Where is the event?"
      answer: >
        The event is being hosted at DePaul University's loop campus. Primarily In the CDM building located at  243 S Wabash Ave, Chicago, IL 60604.
    - question: "What is Major League Hacking?"
      answer: >
        Major League Hacking is [the official student hackathon league](https://mlh.io) in North America & Europe.
        We work with over 200 Member Events and empower over 70,000 students every year.
    - question: "Is there a code of conduct?"
      answer: >
        Yes there is, you can [find it here](https://static.mlh.io/docs/mlh-code-of-conduct.pdf).
  
  # sched mockup - Mack
  schedule:
    - day: "Day 1"
      event: >
        6:00am Breakfast
        12:00pm Lunch
        6:00pm Dinner
    - day: "Day 2"
      event: >
        6:00am Breakfast
        12:00pm Lunch
        6:00pm Dinner
    - day: "Day 3"
      event: >
        6:00am Breakfast
        12:00pm Lunch
        6:00pm Dinner
  
  # This is the message you'll receive once you've registered.
  register:
    message: >
      You'll receive more information closer to the hackathon.

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
