# --------------
# -- Settings --
# --------------

# Ignore this. This is only if you're hosting this in a sub-folder.
# If you're using GitHub pages, they automatically override this with the right value.
baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "https://hackuno.com"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-43729070-14"

# Let people connect & engage with you through social media.
#social:
#  twitter_handle: "MLHacks"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "HackUNO | 7/8 March 2020"
  description: "HackUNO is a 24 hour coding marathon that encourages teams to think outside the box and find creative solutions to real world problems! After the 24 hours, teams will present what they have created to a panel of judges that consists of UNO students and companies from the Omaha area, who will decide the winners!"
  image:       "https://prime.mlh.io/img/logos/mlh-prime-color.svg"

# Event information.
event:
  name:        "HackUNO"
  description: "HackUNO is a 24 hour coding marathon that encourages teams to think outside the box and find creative solutions to real world problems!"
  date:        "7 & 8 March 2020"
  location:    "Omaha, NE, United States"

  hero:
    links:
      - text: "Apply"
        href: "https://forms.gle/jZzxu9MYLVLLqB1M9"
      - text: "Sponsor"
        href: "mailto:unoacm@unomaha.edu"

  about:
    description: >
      HackUNO is a 24 hour coding marathon that encourages teams to think outside the box and find creative solutions 
      to real world problems! After the 24 hours, teams will present what they have created to a panel of judges that 
      consists of UNO students and companies from the Omaha area, who will decide the winners!

  # Info Sections
  info:
    sections:
      - image: "images/square.png"
        title: "LEARN."
        description: >
          Pickup new technologies in a collaborative and friendly environment.
      - image: "images/gear.png"
        title: "BUILD."
        description: >
          Create awesome software and hardware projects.
      - image: "images/nodes.png"
        title: "SHARE."
        description: >
          Show off your project to judges and win prizes.
          
  sponsors:
    - image: "images/fnbo_1.jpg"
      title: "First National Bank of Omaha"

  # Frequently asked questions.
  faq:
    - question: "What is a hackathon?"
      answer: >
        A Hackathon is a short development sprint that has teams develop and prototype an unique idea, whether 
        hardware or software. Teams are encouraged to focus on keeping an idea simple and useful while programming 
        the core features of their idea.
    - question: "How much does it cost?"
      answer: >
        Nothing! Food, drinks, and snacks are all provided!
    - question: "Do I need to be a student to attend?"
      answer: >
        Yes. Only students who are currently enrolled at a college/university or
        have graduated within the past 12 months are eligible to attend.
    - question: "Where is the event?"
      answer: >
        The event is being hosted at the Peter Kiewit Institute at the University of Nebraska at Omaha campus in Omaha, Nebraska.
    #- question: "What is Major League Hacking?"
    #  answer: >
    #    Major League Hacking is [the official student hackathon league](https://mlh.io) in North America & Europe.
    #    We work with over 200 Member Events and empower over 70,000 students every year.
    - question: "Is there a code of conduct?"
      answer: >
        Yes there is. We enforce it very strongly. You can [find it here](https://static.mlh.io/docs/mlh-code-of-conduct.pdf).
    - question: "How big can a team be?"
      answer: >
        Teams can be as small as 1 and as large as 3.
    - question: "Is there a theme?"
      answer: >
        The theme for HackUNO 2020 is going to be weather!
    - question: "Is there a schedule available?"
      answer: >
        The schedule for HackUNO 2020 is still being decided.
    - question: "Will there be prizes?"
      answer: >
        The prizes for HackUNO are still being decided.

  # This is the message you'll receive once you've registered.
  register:
    message: >
      You'll receive more information closer to the hackathon.

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME

theme: jekyll-theme-cayman
