# --------------
# -- Settings --
# --------------

# If you are hosting in a sub-folder, for example: https://mlh.github.io/mlh-hackathon-boilerplate/,
# you must specify it as the baseurl
# If you hosting as a root, for example: htttps://[github username].github.io, then leave it blank
baseurl: "/NGPiTECH-henosis"

# uncomment the next line if you are hosting as a root and not sub-folder
# for example, when runnig locally at http://127.0.0.1:4000/
# baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "https://surprisedPikachu007.github.io"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-43729070-14"

# Let people connect & engage with you through social media.
social:
  twitter_handle: "drngpit"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "Henosis | 25 February 2023"
  description: "Henosis, the National level tech fest conducted by the Departmet of Computer Science and Engineering at NGPiTECH."
  image:       "https://www.drngpit.ac.in/assets/images/logo/ngp-itech-logo.png"

# Event information.
event:
  name:        "Henosis 2K23"
  description: "Henosis, A National level tech fest conducted by the Departmet of Computer Science and Engineering at NGPiTECH."
  date:        "25 February 2023"
  location:    "Coimbatore, Tamil Nadu, India"

  trust_badge:
    year:   "2017"  # season year
    region: "eu"    # "na" or "eu"
    color:  "white" # "white", "black", "gray", "red", "blue" or "yellow"

  hero:
    links:
      - text: "Register Here"
        my_mlh:
          client_id:    "0e2f9fc2921d3ad3e12ae900af630d09382e1b3dc1b5b50de2b01b70ad64dbee"
          redirect_uri: "https://mlh.github.io/mlh-hackathon-boilerplate/success.html"
      

  about:
    description: >
      This is a one day event. There are four technical events which are fun. And OH!, did we forget to mention that there are exciting rewards for the top participants.

  # Info Sections
  info:
    sections:
      - image: "images/image1.png"
        title: "THINK."
        description: >
           Think big, start small
      - image: "images/image2.png"
        title: "CREATE."
        description: >
          Create a vision, make it a reality.
      - image: "images/image3.png"
        title: "INNOVATE."
        description: >
          Innovate to solve problems and create solutions.
      - image: "images/Code wars.png"
        title: "CODE WARS"
        description: >

  # Frequently asked questions.
  faq:
    - question: "What are the events conducted?"
      answer: >
        A hackathon is an invention marathon. Students come together to build cool
        software & hardware hacks over 24-48 hours. It's [very beginner friendly](https://medium.com/@tfogo/hackathons-are-for-beginners-77a9c9c0e000#.cj21niskl).
    - question: "How many members can participate as a team?"
      answer: >
        Nothing. Attending a hackathon is free.
    - question: "At what time events will commences?"
      answer: >
        Yes. Only students who are currently enrolled at a college/university or
        have graduated within the past 12 months are eligible to attend.
    - question: "How much registration amount to be paid for a member in a team?"
      answer: >
        The event is being hosted at [insert venue location here].
    - question: "What is the last date to register for the fest?"
      answer: >
        Major League Hacking is [the official student hackathon league](https://mlh.io) in North America & Europe.
        We work with over 200 Member Events and empower over 70,000 students every year.
    - question: "What is the registration amount to be paid per team?"
      answer: >
        Yes there is. We enforce it very strongly. You can [find it here](https://static.mlh.io/docs/mlh-code-of-conduct.pdf).
    - question: ""
      answer: >
  # This is the message you'll receive once you've registered.
  register:
    message: >
      You'll receive more information closer to the hackathon.

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
