# --------------
# -- Settings --
# --------------

#coder table done by brittany walker 
#https://codepen.io/trekkiegirl/pen/mWLWJy


# Ignore this. This is only if you're hosting this in a sub-folder.
# If you're using GitHub pages, they automatically override this with the right value.
baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "https://ferrufino.github.io"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-43729070-14"

# Let people connect & engage with you through social media.
social:
  twitter_handle: "MLHacks"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "HackBo"
  description: "Hackathon Clubes de Ciencia Bolivia Santa Cruz de la Sierra"
  image:       ""

# Event information.
event:
  name:        "HackBo"
  description: "Clubes de Ciencia Bolivia"
  date:        "27 de Julio 2017"
  location:    "Santa Cruz de la Sierra, Bolivia"

  hero:
    links:
      - text: "Aplica"
        href: "https://ferrufino.typeform.com/to/jDxP1F"
      - text: "Auspicianos"
        href: "mailto:ferru@test.com"

  about:
    description: >
      HackBo es un hackathon estudiantil donde apasionados por la tecnología colaboran durante 24hrs. 
      entre equipos y compiten para crear la mejor solución de software o hardware 
      y ganar uno de los tres primeros lugares, y obviamente, premios!      

  # Info Sections
  info:
    sections:
      - image: "images/design.png"
        title: "DISEÑA."
        description: >
          Diseña bien tu proyecto! Deberías de ser capaz de responder ¿Que necesidad soluciona mi propuesta?
          (Impacto Civico, Saludo, Social, etc.)
      - image: "images/develop.png"
        title: "DESARROLLA."
        description: >
          Tu desarrollo debe de ser un programa de software o de electronica. 
          Si durante el hackathon tienes dudas no te preocupes, tendres grandes mentores para asesorarte. ;) 
      - image: "images/present.png"
        title: "PRESENTA."
        description: >
          Asegurate que tu hack este estable, y prepara la presentación ante los jueces! Buena suerte!

  # Frequently asked questions.
  faq:
    - question: "¿Que es un Hackathon?"
      answer: >
        Un hackathon es un maratón de creadores. Estudiantes se juntan para crear cool Software y Hardware hacks en 24hrs.
    - question: "¿Cuanto Cuesta?"
      answer: >
        Nada. Atender el Hackathon es gratis
    - question: "¿Necesito ser estudiante para atender este Hackathon?"
      answer: >
        Si. Solo estudiantes que esten inscritos en universidad o bien ultimos años de colegio (con permiso de su tutor legal)
        pueden participar de este evento.
    - question: "¿Donde es el evento?"
      answer: >
        El evento va ser realizado en la UPSA del 27 al 28 de Julio
    - question: "¿Existe un codigo de conducta?"
      answer: >
        Si existe. Lo vamos a enforcar y respetar en su plenitud. Puedes encontrarlo [aqui](https://static.mlh.io/docs/mlh-code-of-conduct.pdf).
    - question: "¿Quienes estan organizando este evento?"
      answer: >
        [Clubes de Ciencia Bolivia](http://www.clubesdecienciabolivia.com/)

  # Partners
  partner:
    - image: "images/upsa.png"

  # This is the message you'll receive once you've registered.
  register:
    message: >
      You'll receive more information closer to the hackathon.

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
