# bundle exec jekyll serve
#--------------
# -- Settings --
# --------------

#coder table done by brittany walker 
#https://codepen.io/trekkiegirl/pen/mWLWJy


# Ignore this. This is only if you're hosting this in a sub-folder.
# If you're using GitHub pages, they automatically override this with the right value.
baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "http://www.hackbo.org"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-43729070-14"

# Let people connect & engage with you through social media.
social:
  twitter_handle: "HackBo"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "HackBo"
  description: "Hackathon Clubes de Ciencia Bolivia Santa Cruz de la Sierra"
  image:       ""

# Event information.
event:
  name:        "HackBo"
  description: "Clubes de Ciencia Bolivia"
  date:        "27 y 28 de Julio 2017"
  location:    "UPSA"

  hero:
    links:
      - text: "Aplica"
        href: "https://ferrufino.typeform.com/to/jDxP1F"
        class: "typeform-share link"
        data-mode: "2"
        target: "_blank"
      - text: "Patrocinios"
        href: "mailto:ferru@test.com"
        class: ""
        data-mode: ""
        target: ""

  about:
    description: >
      HackBo es el hackathon estudiantil más grande en Bolivia, donde apasionados por la tecnología colaboran durante 24hrs. 
      entre equipos y compiten para desarrollar la mejor solución de software o hardware 
      y ganar uno de los tres primeros lugares, al igual que premios!      

  # Info Sections
  info:
    sections:
      - image: "images/Disenha.png"
        title: "DISEÑA"
        description: >
          Diseña bien tu proyecto! Deberías de ser capaz de responder ¿Que necesidad soluciona mi propuesta?
          (Civico, Salud, Social, Educacion, etc.)
      - image: "images/Desarrolla.png"
        title: "DESARROLLA"
        description: >
          Debe de ser un proyecto de software o hardware. 
          Si durante el hackathon tienes dudas, no te preocupes, tendras grandes mentores para que te asesoren. ;) 
      - image: "images/Presenta.png"
        title: "PRESENTA"
        description: >
          Asegurate que tu hack este estable, y no te olvides de preparar tu presentación ante los jueces. Buena suerte!

  # Frequently asked questions.
  faq:
    - question: "¿Que es un Hackathon?"
      answer: >
        Un hackathon es un maratón de creadores. Estudiantes se juntan para crear un proyecto cool de Software o Hardware en 24hrs.
    - question: "¿Cuanto Cuesta?"
      answer: >
        Nada. Atender el Hackathon es gratis.
    - question: "¿Necesito ser estudiante para atender este Hackathon?"
      answer: >
        Si. Solo estudiantes que esten inscritos en universidad o bien ultimos años de colegio (con permiso de su tutor legal)
        pueden participar de este evento.
    - question: "¿Donde es el evento?"
      answer: >
        El evento va ser realizado en la UPSA del 27 al 28 de Julio
    - question: "¿Existe un codigo de conducta?"
      answer: >
        Si existe. Participantes deben de respetar esto en su plenitud. Puedes encontrarlo [aqui](https://static.mlh.io/docs/mlh-code-of-conduct.pdf).
    - question: "¿Quienes estan organizando este evento?"
      answer: >
        [Clubes de Ciencia Bolivia](http://www.clubesdecienciabolivia.com/)

  # Partners
  partner:
    - image: "images/upsa.png"

  logo:
    - image: "images/hackbo2x.png"
    - imageSmall: "images/hackbo.png"
    - imageCdeCBo: "images/CdeCBo@2x.png"

  # This is the message you'll receive once you've registered.
  register:
    message: >
      You'll receive more information closer to the hackathon.

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
